version: "3.8"

services:
  database:
    image: postgres:13.3
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 10s
      timeout: 20s
      retries: 5
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=Goods
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      test-task:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/Goods
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=1234
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      test-task:

networks:
  test-task:
    name: test-task


volumes:
  postgres:
    name: postgresww