spring:
  application:
    name: TestTaskMediaSoft

  config:
    profiles:
      active: "dev-postgresql"

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/Goods}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

---
spring:
  application:
    name: TestTaskMediaSoft

  config:
    profiles:
      active: "dev-h2"

  datasource:
      url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:Goods}
      username: ${SPRING_DATASOURCE_USERNAME:user}
      password: ${SPRING_DATASOURCE_PASSWORD:1234}
      driverClassName: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

server:
  port: ${SERVER_PORT:8080}